# Generated by Django 3.2.13 on 2022-04-12 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DONE', 'Done'), ('IN WORK', 'In work'), ('CANCELED', 'Canceled'), ('CREATED', 'Created')], default='Created', max_length=50)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('complete_date', models.DateTimeField(blank=True)),
                ('products', models.ManyToManyField(to='shop_app.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
