# Generated by Django 3.2.13 on 2022-04-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
