# Generated by Django 3.2.13 on 2022-04-12 13:08

import django.contrib.postgres.fields
from django.db import migrations, models
import shop_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_order_complete_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=shop_app.models.get_default, size=None),
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=shop_app.models.get_default, size=None),
        ),
    ]
