# Generated by Django 3.2.13 on 2022-05-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_auto_20220511_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='media/default.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='media/default.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='media/default.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(default='media/default.png', upload_to='media/'),
        ),
    ]
